### ISSUE TITLE
Would you consider VLAN and bridge support ?

### ISSUE THREAD

**Issue by galaxy001** [Rudd-O/qubes-network-server#11]
Suppose we have a managed switch which support VLAN with trunk port, and also supports layer 3 route.

I want to expose some appVM to a local VLAN to be shared with other machines.
The "sys-net" vm should be able to bridge trusted local VLANs directly, while keep the ISP public VLAN untrusted with NAT.

I find sth. on bridge on Qubes R2:
https://www.qubes-os.org/doc/network-bridge-support/

**Comment by Rudd-O** [comment]
I wouldn't know where to start, and I couldn't test it either since I don't really have a VLAN-supporting switch connected to my Qubes OS lab.  But if you can come up with the code for that feature, and possibly some tests we can run on the code, I would be extremely happy to incorporate that code.
