### ISSUE TITLE
Integrating OPNSense

### ISSUE THREAD

**Issue by ProfessorManhattan** [Rudd-O/qubes-network-server#14]
Do you know what would be involved with integrating OPNSense with this setup?

**Comment by Rudd-O** [comment]
Nope, I am not familiar with FreeBSD or how to run it under Qubes OS.

**Comment by ProfessorManhattan** [comment]
Still working on it myself but it would be a substitute for sysnet and
sysfirewall as an HVM. It needs direct access to the Ethernet so it can't
just be a proxyvm
