### ISSUE TITLE
hvm support

### ISSUE THREAD

**Issue by tlaurion** [Rudd-O/qubes-network-server#4]
@Rudd-O @lamuse @jpouellet : What needs to be done to support HVM mode in Qubes?

**Comment by tlaurion** [comment]
Anyone?

**Comment by tlaurion** [comment]
From : https://groups.google.com/forum/m/#!msg/qubes-users/sNjucuuiCcQ/UyNAnHKjAAAJ

Thank you for opening the ticket.  It may be difficult for me to adapt
to 4.0, so I kindly request anyone with the required skillset to send a
pull request adapting it to 4.0.

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by tlaurion** [comment]
What part of the theory if application is now invalid?

Theory of operation
Qubes OS relies on layer 3 (IP) routing. VMs in its networked tree send traffic through their default route interfaces, which upstream VMs receive and masquerade out of their own default route interfaces.

Qubes network server slightly changes this when a networked VM — a VM which has had its static_ip attribute set with qvm-static-ip — exists on the networked tree. As soon as a networked VM boots up, Qubes network server:

sets a static /32 route on every upstream VM to the networked VM's static IP, directing the upstream VMs to route traffic for that IP to their VIFs where they may find the networked VM
enables ARP neighbor proxying for the static IP on every upstream VM, such that every upstream VM announces itself to their own upstream VMs (and LAN, in the case of NetVMs) as the networked VM
sets firewall rules on every upstream VM that allow normal non-masquerading forwarding to and from the IP of the networked VM
(depending on the Qubes firewall policy of the networked VM) sets rules on every upstream ProxyVM that allow for certain classes of inbound traffic
(depending on the Qubes firewall policy of the networked VM) sets rules directly on the networked VM that allow for certain classes of inbound traffic

**Comment by Rudd-O** [comment]
The new system does not require a Linux shell in the AppVM.  This should just work now.
