### ISSUE TITLE
Porting to qubesadmin required

### ISSUE THREAD

**Issue by tlaurion** [Rudd-O/qubes-network-server#5]
[This](https://github.com/Rudd-O/qubes-network-server/blob/3847a3745682a6b079937d8a9f6c08adb4e657cc/src/usr/bin/qvm-static-ip#L24)

Needs to be ported to [qubesadmin](https://github.com/QubesOS/qubes-core-admin/pull/171/files) 
```
-from qubes.qubes import QubesVmCollection
+from qubesadmin import Qubes
```

**Comment by Rudd-O** [comment]
Qubesadmin port complete on `master`.
