### ISSUE TITLE
Does this work with 4.0?

### ISSUE THREAD

**Issue by sneurlax** [Rudd-O/qubes-network-server#6]
I'd like to use this with 4.0, have you tested it yet?

**Comment by Rudd-O** [comment]
Not yet and chances are it won't.  Things are different.  I intend to make a port once I return from my trip.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sneurlax** [comment]
Wonderful, sorry for the issue.  Shall I close it?

**Comment by Rudd-O** [comment]
We need it open to remind us to do the port.

On April 29, 2018 12:03:02 AM GMT+02:00, sneurlax <notifications@github.com> wrote:
>Wonderful, sorry for the issue.  Shall I close it?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Rudd-O/qubes-network-server/issues/6#issuecomment-385208484

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tlaurion** [comment]
Best would be to be able to select "to" and "from" qubes directly from the
firewall GUI.

Really looking into this port, @Rudd-O! :)

**Comment by tlaurion** [comment]
[Best effort](https://github.com/niccokunzmann/qvm-expose-port) to date

**Comment by Rudd-O** [comment]
4.0 support is done.
Unfortunately, we had to drop the firewalling from the port — at least until a later time.  You will have to use the `rc.local` method of controlling your AppVM's firewall directly.
> Best would be to be able to select "to" and "from" qubes directly from the firewall GUI.
Sorry we couldn't get to this before release.  It's in the to-do list within the repo.
