### ISSUE TITLE
Create Firewall rules (from- to-)

### ISSUE THREAD

**Issue by tlaurion** [Rudd-O/qubes-network-server#9]
per https://github.com/Rudd-O/qubes-network-server/pull/1#issuecomment-613380822 to modify QubesOS firewall GUI to permit _to-_ and _from-_ statements:

@Rudd-O said about QubeSOS 3.2 version:
> The previous code "hacked" qubes-firewall at runtime to support rules with from- prefixes. This proved very hard to maintain, so I pulled that code out (it's still in the release-3.2 branch).
> 
> The correct thing to do here is to extend the admin core so that a rule can specify its direction, and a compatible change to qubes-firewall on the agent side does the right thing.
> 
> At the moment Qubes network server doesn't do anything special to the forwarding rules — except for allowing VIF-to-VIF traffic — because the default for ProxyVMs is to forward traffic to their connected VMs.

@marmarek: Any cooperation on this in regard of actual 4.0 and 4.1 branches on this project?

**Comment by Rudd-O** [comment]
We've removed the feature that allows ProxyVMs to be interposed, sadly.  There was no reasonable way to support it.  However, you can still set up AppVM firewall rules.
